sudo: required
services:
  - docker

before_install:
  - docker build -t habichta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true habichta/react-test npm test

after_success:
  - docker build -t habichta/multi-client ./client
  - docker build -t habichta/multi-nginx ./nginx
  - docker build -t habichta/multi-server ./server
  - docker build -t habichta/multi-worker ./worker
  # Log in to Docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push habichta/multi-client 
  - docker push habichta/multi-nginx 
  - docker push habichta/multi-server 
  - docker push habichta/multi-worker 


deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-084506881259
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY